server:
  port: 80
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/ymail?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#    username: root
#    password: Ii*142857
#    url: jdbc:mysql://slovety.top:9527/ymail?characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver


    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

rocketmq:
  name-server: 127.0.0.1:9876 # 访问地址
#  name-server: 47.106.217.20:9876 # 访问地址
  producer:
    group: Pro_Group # 必须指定group
    send-message-timeout: 10000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
damin:
  sad